# Generated by Django 5.1.4 on 2026-10-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='target_per_hour',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=7),
        ),
    ]
