# Generated by Django 5.1.4 on 2026-10-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_driverprofile_target_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridehistory',
            name='classification',
            field=models.CharField(choices=[('GREEN', 'Verde'), ('YELLOW', 'Amarela'), ('RED', 'Vermelha'), ('RISK_RED', 'Área de risco')], max_length=8),
        ),
    ]
