# Generated by Django 5.1.4 on 2026-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ridehistory_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='daily_goal',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=10),
        ),
    ]
