# Generated by Django 5.1.4 on 2026-10-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_driverprofile_daily_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridehistory',
            name='dropoff',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='ridehistory',
            name='pickup',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
    ]
