# Generated by Django 5.1.4 on 2026-10-02 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ridehistory_dropoff_ridehistory_pickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanicAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Quando o motorista disparou o alerta.')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('transcript', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('em_atendimento', 'Em atendimento'), ('encerrado', 'Encerrado')], default='ativo', max_length=16)),
                ('operator_action', models.CharField(blank=True, choices=[('acionar_policia', 'Acionar polícia'), ('contato_ativo', 'Contato ativo'), ('falso_positivo', 'Falso positivo')], max_length=16, null=True)),
                ('is_test', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.driverprofile')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
