# Generated by Django 5.1.4 on 2026-10-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_panicalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='panicalert',
            name='origin',
            field=models.CharField(choices=[('APP', 'App (toque)'), ('VOZ', 'Frase de voz'), ('BOTAO_PANICO', 'Botão físico (ESP32)'), ('TESTE', 'Teste')], default='APP', help_text='Como o alerta foi disparado (voz, botão físico, etc.).', max_length=16),
        ),
    ]
