package com.copiloto.motorista.data.model

/**
 * Origin of a ride offer. Package names match the apps monitored by the
 * [com.copiloto.motorista.service.RideAccessibilityService].
 */
enum class RideSource(val displayName: String, val packageName: String?) {
    UBER("Uber", "com.ubercab.driver"),
    NINETY_NINE("99", "com.taxis99"),
    INDRIVE("inDrive", "sinet.startup.inDriver"),
    SIMULATOR("Simulador", null),
    OTHER("Outro app", null),
    UNKNOWN("Desconhecido", null);

    companion object {
        /** The apps shipped as monitored by default (they have a known package). */
        val BUILT_INS: List<RideSource> = listOf(UBER, NINETY_NINE, INDRIVE)

        fun fromPackage(packageName: String?): RideSource =
            entries.firstOrNull { it.packageName == packageName } ?: UNKNOWN
    }
}

/**
 * A rideshare/delivery app the driver chose to monitor on top of the built-ins.
 */
data class MonitoredApp(val packageName: String, val label: String)

/**
 * A ride offer as extracted from the screen (Module A) or generated by the
 * simulator (Module G), before any profitability math is applied.
 */
data class RideOffer(
    val source: RideSource,
    val grossPrice: Double,
    val distanceKm: Double,
    val timeMinutes: Int,
    val pickup: String? = null,
    val dropoff: String? = null,
    val rawText: String? = null,
    /** Label of a user-added app ([RideSource.OTHER]); null for built-in sources. */
    val sourceLabel: String? = null,
    /** Generated by the in-app simulator (Module G) for a demo — accepting it opens
     *  the in-trip demo screen (map + animated route). Real scraped offers stay false. */
    val isDemo: Boolean = false,
) {
    /** An offer is only actionable when it carries the numbers the engine needs. */
    val isComplete: Boolean
        get() = grossPrice > 0.0 && distanceKm > 0.0 && timeMinutes > 0

    /** Human name to display: the custom app label when present, else the source name. */
    val displayLabel: String
        get() = sourceLabel?.takeIf { it.isNotBlank() } ?: source.displayName
}

/**
 * Traffic-light recommendation for a ride. [RISK_RED] is a hard safety override:
 * the destination matched a risk-zone keyword, so the profitability math is
 * ignored and the ride is flagged as a risk area.
 */
enum class RideClassification { GREEN, YELLOW, RED, RISK_RED }

/**
 * Result of running a [RideOffer] through the Calculation Engine (Module B).
 */
data class RideEvaluation(
    val offer: RideOffer,
    val costPerKm: Double,
    val totalCost: Double,
    val grossPerKm: Double,
    val grossPerHour: Double,
    val netProfit: Double,
    val classification: RideClassification,
)
